version: '3'

services:
  feaster.of.domains.users:
    image: feaster.of.domain.users
    build:
      context: ./FeasterOfDomains.Users
      dockerfile: Dockerfile
    depends_on:
      - sql.data
    environment:     
      ConnectionString: "Server=sql.data;Database=Users;User=sa;Password=268705b8-bba5-4c58-93d2-7da19c98590f;"
    ports:
      - 10000:80

  sql.data:
    image: "microsoft/mssql-server-linux:2017-GA"
    environment:
        SA_PASSWORD: "268705b8-bba5-4c58-93d2-7da19c98590f"
        ACCEPT_EULA: "Y"    
    volumes:
      - /c/temp/amtrust/containers/identityserver/mssql:/var/opt/mssql
    ports:
      - 1433:1433